# Generated by Django 6.0.1 on 2026-01-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='owner_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
