# Generated by Django 6.0.1 on 2026-01-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
